name       : grafx2
version    : 2.4.2035
release    : 1
source     :
    - http://pulkomandy.tk/projects/GrafX2/downloads/21 : 5818caea63cd3cf3318baf01dd20f81ec61e4514443000c80a41b68ab3f17a6b
license    : GPL-2.0
component  : multimedia.graphics
summary    : GrafX2 is a drawing program dedicated to pixelart and low-color graphics.
description: |
    GrafX2 is a drawing program dedicated to pixelart and low-color graphics.
builddeps  :
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_ttf)
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(x11)
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-reference-correct-header-locations-for-lua.patch
build      : |
    pushd src
    %make
    popd
install    : |
    pushd src
    %make_install prefix=/usr
    popd
