name       : grafx2
version    : '2.4'
release    : 3
source     :
    - https://gitlab.com/GrafX2/grafX2/-/archive/v2.4/grafX2-v2.4.tar.bz2 : 1f662916f00f0ddb1ffbafbcc4203c5f2f61425e1a8e7118dc93054de1544a2e
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : GrafX2 is a drawing program dedicated to pixelart and low-color graphics
description: |
    GrafX2 is a drawing program dedicated to pixelart and low-color graphics.
builddeps  :
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_ttf)
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(x11)
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-reference-correct-header-locations-for-lua.patch
build      : |
    %make -C src
install    : |
    %make_install -C src prefix=/usr
