name       : grafx2
version    : '2.7'
release    : 6
source     :
    - https://gitlab.com/GrafX2/grafX2/-/archive/v2.7/grafX2-v2.7.tar.bz2 : 21ff3c2985b0a870afd0ca962abfc7af5f75b7f21408c74072f1becee83def1e
homepage   : http://grafx2.tk
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : GrafX2 is a drawing program dedicated to pixelart and low-color graphics
description: |
    GrafX2 is a bitmap paint program inspired by the Amiga programs Deluxe Paint and Brilliance. Specialized in 256-color drawing, it includes a very large number of tools and effects that make it particularly suitable for pixel art, game graphics, and generally any detailed graphics painted with a mouse.
networking : yes
builddeps  :
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_ttf)
    - pkgconfig(fontconfig)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(lua-5.1)
    - pkgconfig(x11)
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-reference-correct-header-locations-for-lua.patch
build      : |
    %make -C src
install    : |
    %make_install -C src PREFIX=/usr
    mv $installdir/usr/bin/grafx2-sdl $installdir/usr/bin/grafx2
